name: Build & Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    if: github.repository == 'Protofy-xyz/Vento'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: yarn

      - name: Prepare dev
        run: yarn prepare-dev-ci

      - name: Shrink
        run: yarn shrink

      - name: Create release zip
        run: |
          zip -r release-${GITHUB_REF_NAME}.zip . -x ".git/*" "node_modules/*" "release-*.zip" "vento-pages.zip"

      - name: Create pages zip
        run: |
          zip -r vento-pages.zip data/pages

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            release-${{ github.ref_name }}.zip
            vento-pages.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
