name: Build & Release Development

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.repository == 'Protofy-xyz/Vento'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: node scripts/enableUiDev.js && YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install --mode=update-lockfile

      - name: Prepare dev
        run: yarn prepare-dev-ci

      - name: Shrink
        run: yarn shrink

      - name: Create release zip
        run: |
          zip -r release-development.zip . -x ".git/*" "node_modules/*" "release-*.zip" "vento-pages.zip"

      - name: Create pages zip
        run: |
          zip -r vento-pages.zip data/pages

      - name: Create or update development tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -f development
          git push origin -f development

      - name: Create GitHub Release (development)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: development
          name: development release
          files: |
            release-development.zip
            vento-pages.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}